blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('posts.urls', namespace='blog'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.views import viwe_posts, view_detail, view_form ,edit_post, delete_post
from posts.views2 import Postlist, PostDetail, AddPost, EditPost, DeletePost

app_name='posts'

urlpatterns = [
    path('', Postlist.as_view() ,name='view_posts'),
    path('<int:pk>', PostDetail.as_view(), name='details'),
    path('form', AddPost.as_view(), name='new_post'),
    path('<int:pk>/edit', EditPost.as_view(), name='edit'),
    path('<int:pk>/delete', DeletePost.as_view(), name='delete'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.
class Post(models.Model):
    auther = models.ForeignKey(User,on_delete=models.CASCADE ,related_name='poastUser')
    title = models.CharField(max_length=100)
    content = models.TextField(max_length=5000)
    active = models.BooleanField(default=False)
    image = models.ImageField(upload_to='post/', null=True , blank=True) 

    def __str__(self):
        return self.title

posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta :
        model = Post 
        #fields = '__all__'
        exclude = ['auther']

posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm
from django.urls import reverse

# Create your views here.
def viwe_posts(request):
    objects = Post.objects.all()
    return render(request, 'posts/posts.html',{'posts':objects})

def view_detail(request,id):
    single_post = Post.objects.get(id=id)
    return render(request, 'posts/post_detail.html',{'post':single_post})

def view_form(request):
    if request.method == 'POST' :
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            myForm = form.save(commit=False)
            myForm.auther = request.user
            myForm.save()
            return redirect(reverse('blog:view_posts'))
    else:
        form = PostForm()
    return render(request, 'posts/form.html',{'form':form})

def edit_post(request,id):
    single_post = Post.objects.get(id=id)
    if request.method == 'POST' :
        form = PostForm(request.POST, request.FILES, instance=single_post) 
        if form.is_valid():
            form.save()
    else:
        form = PostForm(instance=single_post)
    return render(request, 'posts/edit.html',{'form':form})  

def delete_post(request,id):
    single_post = Post.objects.get(id=id)
    single_post.delete()
    return redirect(reverse('blog:view_posts'))
    

posts/templates/posts/edit.html
<h3>edit post</h3>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form }}
    <input type="submit" value="save">
</form>

posts/templates/posts/post_confirm_delete.html
<form method="post">
     
    {% csrf_token %}
    <p>Are You Sure You Want To Delete{{post}}</p>
    <input type="submit" value="confirm">
</form>

posts/templates/posts/post_detail.html
{% extends "base.html" %}
{% block body %}
<div class="main-wrapper">
	<article class="blog-post px-3 py-5 p-md-5">
		<div class="container single-col-max-width">
			<header class="blog-post-header">
				<h2 class="title mb-2">{{post}}</h2>
				<div class="meta mb-3"><span class="date">Published 2 days ago</span><span class="time">5 min
						read</span><span class="comment"><a class="text-link" href="#">4 comments</a></span></div>
			</header>

			<div class="blog-post-body">
				<figure class="blog-banner">
					<img src="{{post.image.url}}" alt="" width=200px>
				</figure>
				<p> {{post.content}}</p>
				
					{% endblock body %}

posts/templates/posts/post_detail2.html
<h1>post detail</h1>

<h3>{{post}}</h3>

<p>{{post.content}}</p>

<img src="{{post.image.url}}" alt="" width=200px>

<a href="{% url 'blog:edit' post.id %}">Edit Post</a>
<a href="{% url 'blog:delete' post.id%}">Delete Post</a>

posts/templates/posts/post_form.html
<h3>create post</h3>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form }}
    <input type="submit" value="submit">
</form>

posts/templates/posts/post_list.html
{% extends "base.html" %}   
{% block body %}
    <div class="main-wrapper">
	    
	    <section class="cta-section theme-bg-light py-5">
		    <div class="container text-center single-col-max-width">
			    <h2 class="heading">DevBlog - A Blog Template Made For Developers</h2>
			    <div class="intro">Welcome to my blog. Subscribe and get my latest blog post in your inbox.</div>
			    <div class="single-form-max-width pt-3 mx-auto">
				    <form class="signup-form row g-2 g-lg-2 align-items-center">
	                    <div class="col-12 col-md-9">
	                        <label class="sr-only" for="semail">Your email</label>
	                        <input type="email" id="semail" name="semail1" class="form-control me-md-1 semail" placeholder="Enter email">
	                    </div>
	                    <div class="col-12 col-md-2">
	                        <button type="submit" class="btn btn-primary">Subscribe</button>
	                    </div>
	                </form><!--//signup-form-->
			    </div><!--//single-form-max-width-->
		    </div><!--//container-->
	    </section>
	    
	    
	    <section class="blog-list px-3 py-5 p-md-5">
		    <div class="container single-col-max-width">
			    <div class="item mb-5">
				    <div class="row g-3 g-xl-0">
					    <div class="col-2 col-xl-3">
					        <img class="img-fluid post-thumb " src="images/blog/blog-post-thumb-1.jpg" alt="image">
					    </div>
					    <div class="col">
							{% for post in post_list  %}
						    <h3 class="title mb-1"><a class="text-link" href="{% url "blog:details" post.id %}">{{post}}</a></h3>
						    <div class="meta mb-1"><span class="date">Published 2 days ago</span><span class="time">5 min read</span><span class="comment"><a class="text-link" href="#">8 comments</a></span></div>
						    <div class="intro">{{post.content}} </div>
						    <a class="text-link" href="{% url "blog:details" post.id %}">Read more &rarr;</a>
							{% endfor %}
					    </div><!--//col-->
				    </div><!--//row-->
			    </div><!--//item-->
			    
			    <nav class="blog-nav nav nav-justified my-5">
				  <a class="nav-link-prev nav-item nav-link d-none rounded-left" href="#">Previous<i class="arrow-prev fas fa-long-arrow-alt-left"></i></a>
				  <a class="nav-link-next nav-item nav-link rounded" href="#">Next<i class="arrow-next fas fa-long-arrow-alt-right"></i></a>
				</nav>
				
		    </div>
	    </section>
	</div><!--//main-wrapper-->    
		{% endblock body %} 

posts/templates/posts/post_list2.html
<h1> blog </h1>

<a href="{% url "blog:new_post"%}">creat new post</a>
<hr>

{% for post in post_list  %}

    <h3> <a href="{% url "blog:details" post.id %}">{{post}}</a> </h3>

{% endfor %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>DevBlog - Bootstrap 5 Blog Template For Developers</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Blog Template">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">    
    <link rel="shortcut icon" href="favicon.ico"> 
    
    <!-- FontAwesome JS-->
	<script defer src="{% static "fontawesome/js/all.min.js" %}"></script>
    
    <!-- Theme CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static "css/theme-1.css" %}">

</head> 
<body>
    
    <header class="header text-center">	    
	    <h1 class="blog-name pt-lg-4 mb-0"><a class="no-text-decoration" href="index.html">Anthony's Blog</a></h1>
        
	    <nav class="navbar navbar-expand-lg navbar-dark" >
           
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div id="navigation" class="collapse navbar-collapse flex-column" >
				<div class="profile-section pt-3 pt-lg-0">
				    <img class="profile-image mb-3 rounded-circle mx-auto" src="assets/images/profile.png" alt="image" >			
					
					<div class="bio mb-3">Hi, my name is Anthony Doe. Briefly introduce yourself here. You can also provide a link to the about page.<br><a href="about.html">Find out more about me</a></div><!--//bio-->
					<ul class="social-list list-inline py-3 mx-auto">
			            <li class="list-inline-item"><a href="#"><i class="fab fa-twitter fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-github-alt fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-stack-overflow fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-codepen fa-fw"></i></a></li>
			        </ul><!--//social-list-->
			        <hr> 
				</div><!--//profile-section-->
				
				<ul class="navbar-nav flex-column text-start">
					<li class="nav-item">
					    <a class="nav-link active" href="index.html"><i class="fas fa-home fa-fw me-2"></i>Blog Home <span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item">
					    <a class="nav-link" href="blog-post.html"><i class="fas fa-bookmark fa-fw me-2"></i>Blog Post</a>
					</li>
					<li class="nav-item">
					    <a class="nav-link" href="about.html"><i class="fas fa-user fa-fw me-2"></i>About Me</a>
					</li>
				</ul>
				
				<div class="my-2 my-md-3">
				    <a class="btn btn-primary" href="https://themes.3rdwavemedia.com/" target="_blank">Get in Touch</a>
				</div>
			</div>
		</nav>
    </header>

    {% block body %}

    {% endblock body %}

    <footer class="footer text-center py-2 theme-bg-dark">
		   
        <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
        <small class="copyright">Designed with <span class="sr-only">love</span><i class="fas fa-heart" style="color: #fb866a;"></i> by <a href="https://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>
       
    </footer>
   
<!-- Javascript -->          
<script src="{% static "plugins/popper.min.js" %}"></script> 
<script src="{% static "plugins/bootstrap/js/bootstrap.min.js" %}"></script> 

</body>
</html>